version: '3.1'

services:
  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gangagsoc2020Root
      MYSQL_DB: gangadb
      MYSQL_USER: gangauser
      MYSQL_PASSWORD: gangagsoc2020
    ports:
      - "3308:3306"
